service: poc-kotlin-lambda-basic
frameworkVersion: '3'
provider:
  name: aws
  runtime: java11

plugins:
  - serverless-wsgi

package:
  artifact: build/libs/poc-kotlin-lambda-basic-dev-all.jar


functions:
  helloWorld:
    handler: com.rodtech.serverless.HelloWorldFunction
    events:
      - http:
          path: /hello
          method: get
