name: Poc Basic kotlin AWS Lambda With Serverless

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #checkout repo
      - uses: actions/checkout@v2
      #configure JDK
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '14'
      #build with gradle
      - name: Build
        run: ./gradlew build
      #add files build on cache to using another job
      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: build/libs
          key: ${{ runner.os }}-build-${{ hashFiles('build/libs/*.jar') }}
  #Deploy AWS hml
  deploy-hml:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Hml
      url: https://test.com
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: .
          include: |
            serverless.yml
      - name: Restore build artifacts
        uses: actions/cache@v2
        with:
          path: build/libs
          key: ${{ runner.os }}-build-${{ hashFiles('build/libs/*.jar') }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to HML
        run: |
          serverless deploy --stage hml --aws-profile default --config serverless.yml --env stage=hml

  #Deploy to AWS prd
  deploy-prd:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Prod
      url: https://test.com
    steps:
      #checkout repo
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: .
          include: |
            serverless.yml
      #get build files
      - name: Restore build artifacts
        uses: actions/cache@v2
        with:
          path: build/libs
          key: ${{ runner.os }}-build-${{ hashFiles('build/libs/*.jar') }}
      #aws config variables
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      #deploy to aws
      - name: Deploy to PRD
        run: |
          serverless deploy --stage prod --aws-profile default --config serverless.yml --env stage=prod
