name: Poc Basic kotlin AWS Lambda With Serverless

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '14'
      - name: Build
        run: ./gradlew build
      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: build/libs
          key: ${{ runner.os }}-build-${{ hashFiles('build/libs/*.jar') }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: .
          include: |
            serverless.yml
      - name: Restore build artifacts
        uses: actions/cache@v2
        with:
          path: build/libs
          key: ${{ runner.os }}-build-${{ hashFiles('build/libs/*.jar') }}
      - name: Install global dependencies
        run: npm install -g serverless
      # Set the AWS credentials as environment variables
      - name: Set AWS credentials as environment variables
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #deploy to aws by serverless framework
      - name: Deploy to AWS
        run: serverless deploy --aws-access-key-id=$AWS_ACCESS_KEY_ID --aws-secret-access-key=$AWS_SECRET_ACCESS_KEY