name: Poc Basic kotlin AWS Lambda With Serverless

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '14'

      - name: Setup Gradle
        uses: gradle/gradle-buidl-action@v2

      - name: Gradle Build
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-buidl-action@v2

      - name: Test
        run: ./gradlew test

  #Deploy AWS hml
#  deploy-hml:
#    needs: [build, test]
#    runs-on: ubuntu-latest
#    environment:
#      name: Hml
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          path: .
#          include: |
#            serverless.yml
#      - name: Restore build artifacts
#        uses: actions/cache@v2
#        with:
#          path: build/libs
#          key: ${{ runner.os }}-build-${{ hashFiles('build/libs/*.jar') }}
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1
#      - name: Deploy to HML
#        uses: serverless/github-action@v3.1
#        with:
#          args: deploy --stage hml --config serverless.yml --package build/libs


  #Deploy to AWS prd
#  deploy-prd:
#    needs: [build, test]
#    runs-on: ubuntu-latest
#    environment:
#      name: Prod
#    steps:
#      #checkout repo
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          path: .
#          include: |
#            serverless.yml
#      #get build files
##      - name: Restore build artifacts
##        uses: actions/cache@v2
##        with:
##          path: build/libs
##          key: ${{ runner.os }}-build-${{ hashFiles('build/libs/*.jar') }}
#      #aws config variables
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1
#      #deploy to aws
#      - name: Deploy to PRD
#        run: |
#          serverless deploy --stage prod --aws-profile default --config serverless.yml --env stage=prod
