name: Poc Basic kotlin AWS Lambda With Serverless

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '14'
      - name: Build
        run: ./gradlew build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install global dependencies
        run: npm install -g serverless
      - name: Configure AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV
      - name: Deploy
        run: serverless deploy